//function pour afficher page membre
function AfficherPageMembre(pageClient){
    //message erreure dans la page inscription
    
    if (pageClient.err){
       var rep= '<div class=\"topnav \" id=\"myTopnav\"  style=\"background-color:#0000de\"; >\n' ;
        rep+='       <a href=\"index.html\"   >Accueill</a>\n' ;
        rep+= '             <div class=\"dropdown\">\n' ;
        rep+= '                 <button class=\"dropbtn\">Gratuit et Échange\n' ;
        rep+= '                      <i class=\"fa fa-caret-down\"></i>\n' ;
        rep+='                  </button>\n' ;
        rep+= '                     <div class=\"dropdown-content\">\n' ;
        rep+= '                       <a href=\"#\">Je cherche</a>\n' ;
        rep+= '                       <a class=\"border\" href=\"#\">J\'offre</a>\n' ;
        rep+= '                     </div>\n' ;
        rep+= '            </div>\n' ;
        rep+='       <a href=\"#contact\">Emplois</a>\n' ;
        rep+= '             <div class=\"dropdown\">\n' ;
        rep+= '                   <button class=\"dropbtn\">Immobilier\n' ;
        rep+='                          <i class=\"fa fa-caret-down\"></i>\n' ;
        rep+= '                   </button>\n' ;
        rep+='                         <div class=\"dropdown-content\">\n' ;
        rep+='                            <a href=\"#\">Sous location</a>\n' ;
        rep+= '                           <a href=\"#\" class=\"border\">Location</a>\n' ;
        rep+= '                           <a href=\"#\" class=\"border\">Colocataire</a>\n' ;
        rep+='                        </div>\n' ;
        rep+='              </div> \n';
        rep+= '      <a href=\"#news\">Forum</a>\n' ;
        rep+= '            <div class=\"dropdown\">\n' ;
        rep+= '                 <button class=\"dropbtn\">Service\n' ;
        rep+= '                     <i class=\"fa fa-caret-down\"></i>\n' ;
        rep+='                  </button>\n' ;
        rep+='                       <div class=\"dropdown-content\">\n' ;
        rep+= '	                           <a href=\"#news\">Information</a>\n' ;
        rep+= '                            <a href=\"#\" class=\"border\">Covoiturage</a>\n' ;
        rep+= '                            <a href=\"#\" class=\"border\">Livraison</a>\n' ;
        rep+= '                     </div>\n' ;
        rep+= '             </div> \n' ;
        rep+='      <div class=\"w3-right\"><a onclick=\"AfficheformInscription()\" href=\"#\">Inscription</a></div>\n' ;
        rep+= '	    <div class=\"w3-right\"><a onclick=\"AfficheformConnexion()\" href=\"#\">Connection</a></div> \n' ;
        rep+='          <a href=\"javascript:void(0);\" class=\"icon\"  onclick=\"myFunction()\"><i  class=\"fa fa-bars\"></i></a>\n' ;
        rep+= '     </div>\n';
				/// inscription ////

		rep+='<div class=\"w3-content \" style=\"max-width:500px\">\n' ;
        rep+= '                 <form   id=\"forminscription\" enctype=\"multitype/form-data\" action=\"/\"  name=\"inscription\" >\n' ;
        rep+= '                       <div class=\"container \"style=\"text-align: center;\" >\n' ;
        rep+= '                                 <h1><b>Créer un compte</b></h1><br>\n' ;
        rep+= '	                                <label for=\"email\"><b>Nom</b></label>\n' ;
        rep+= '                                         <input type=\"text\" placeholder=\"Nom\" name=\"nom\" id=\"nom\" required style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
        rep+= '	\n' ;
        rep+= '	                                <label for=\"email\"><b>Prénom</b></label>\n' ;
        rep+= '                                         <input type=\"text\" placeholder=\"Prénom\" name=\"prenom\" id=\"prenom\" required style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
        rep+= '	\n' ;
        rep+= '	                                <label for=\"email\"><b>Nom d\'utilisateur</b></label>\n' ;
        rep+='                                          <input type=\"text\" placeholder=\"Nom d\'utilisateur\" name=\"username\" id= \"username\" required style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
        rep+= '                                <label for=\"email\"><b>Courriel</b></label>\n' ;
        rep+='                                          <input type=\"text\" placeholder=\"Courriel\" name=\"mail\" id=\"mail\" required style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
        rep+= '\n' ;
        rep+=' <div class=\"alert\">';
        rep+='<span class=\"closebtn\" onclick="this.parentElement.style.display=\'none\';">&times;</span> ';
                if(pageClient.mesgErr){//tester si l'erreur dans le cas ou existe l@ mail
                 rep+= '<strong>Attention!</strong>'+pageClient.mesgErr+'</div>';
                 } else{
                 if(pageClient.msgDins){            //message erreur en cas des champs vide
                    rep+= '<strong>Attention!</strong>'+pageClient.msgDins+'</div>';} }
        rep+= '                                 <label for=\"psw\"><b>Mot de Pass</b></label>\n' ;
        rep+= '                                         <input type=\"password\" placeholder=\"Mot de Pass\" name=\"passe\" id=\"passe\"required style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
        rep+= '\n' ;
        rep+= '                                 <label for=\"psw-repeat\"><b>Confirmer</b></label>\n' ;
        rep+='                                          <input type=\"password\" placeholder=\"Confirmer\" name=\"confirmpasse\" required style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
        rep+='    \n' ;
        rep+='\n';
        rep+='<label>\n' ;
        rep+='</label>\n' ;
        rep+='\n';
        rep+= '                                 <label>\n' ;
        rep+= '                                         <input type=\"checkbox\" checked=\"checked\" name=\"remember\" style=\"margin-bottom:15px\"> Remember me\n' ;
        rep+='                                  </label>\n' ;
        rep+='                                          <input type=\"button\" value=\"Créer\"  onclick=\"requetes(\'inscription\',\'\',\'\',\'\');\" style=\"color:white;font-weight: bold;font-size:20px;;\">\n' ;
        rep+= '                         </div>\n' ;
        rep+= '                 </form>\n' ;
        rep+='          <div style=\"text-align: center;\"><a onclick=\"AfficheformConnexion();\" href=\"#\" style=\"text-decoration-line: none \";><h6> Client existant?s\'enregistrer</h6></a>\n' ;
        rep+='          </div>\n' ;
        rep+='</div>\n' ;
     }else{
         if(pageClient.msgMP){
            var rep= '<div class=\"topnav \" id=\"myTopnav\"  style=\"background-color:#0000de\"; >\n' ;
            rep+='       <a href=\"index.html\"   >Accueill</a>\n' ;
            rep+= '             <div class=\"dropdown\">\n' ;
            rep+= '                 <button class=\"dropbtn\">Gratuit et Échange\n' ;
            rep+= '                      <i class=\"fa fa-caret-down\"></i>\n' ;
            rep+='                  </button>\n' ;
            rep+= '                     <div class=\"dropdown-content\">\n' ;
            rep+= '                       <a href=\"#\">Je cherche</a>\n' ;
            rep+= '                       <a class=\"border\" href=\"#\">J\'offre</a>\n' ;
            rep+= '                     </div>\n' ;
            rep+= '            </div>\n' ;
            rep+='       <a href=\"#contact\">Emplois</a>\n' ;
            rep+= '             <div class=\"dropdown\">\n' ;
            rep+= '                   <button class=\"dropbtn\">Immobilier\n' ;
            rep+='                          <i class=\"fa fa-caret-down\"></i>\n' ;
            rep+= '                   </button>\n' ;
            rep+='                         <div class=\"dropdown-content\">\n' ;
            rep+='                            <a href=\"#\">Sous location</a>\n' ;
            rep+= '                           <a href=\"#\" class=\"border\">Location</a>\n' ;
            rep+= '                           <a href=\"#\" class=\"border\">Colocataire</a>\n' ;
            rep+='                        </div>\n' ;
            rep+='              </div> \n';
            rep+= '      <a href=\"#news\">Forum</a>\n' ;
            rep+= '            <div class=\"dropdown\">\n' ;
            rep+= '                 <button class=\"dropbtn\">Service\n' ;
            rep+= '                     <i class=\"fa fa-caret-down\"></i>\n' ;
            rep+='                  </button>\n' ;
            rep+='                       <div class=\"dropdown-content\">\n' ;
            rep+= '	                           <a href=\"#news\">Information</a>\n' ;
            rep+= '                            <a href=\"#\" class=\"border\">Covoiturage</a>\n' ;
            rep+= '                            <a href=\"#\" class=\"border\">Livraison</a>\n' ;
            rep+= '                     </div>\n' ;
            rep+= '             </div> \n' ;
            rep+='      <div class=\"w3-right\"><a onclick=\"AfficheformInscription()\" href=\"#\">Inscription</a></div>\n' ;
            rep+= '	    <div class=\"w3-right\"><a onclick=\"AfficheformConnexion()\" href=\"#\">Connection</a></div> \n' ;
            rep+='          <a href=\"javascript:void(0);\" class=\"icon\"  onclick=\"myFunction()\"><i  class=\"fa fa-bars\"></i></a>\n' ; 
            rep+= '     </div>\n';
			////conection/////
			rep+='<div class=\"w3-content \" style=\"max-width:500px\">\n' ;
            rep+= '                 <form   id=\"forminscription\" enctype=\"multitype/form-data\" action=\"/\"  name=\"inscription\" >\n' ;
            rep+= '                       <div class=\"container \"style=\"text-align: center;\" >\n' ;
            rep+= '                                 <h1><b>Créer un compte</b></h1><br>\n' ;
            rep+= '	                                <label for=\"email\"><b>Nom</b></label>\n' ;
            rep+= '                                         <input type=\"text\" placeholder=\"Nom\" name=\"nom\" id=\"nom\" required value=\"'+pageClient.nom+'\" style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
            rep+= '	\n' ;
            rep+= '	                                <label for=\"email\"><b>Prénom</b></label>\n' ;
            rep+= '                                         <input type=\"text\" placeholder=\"Prénom\" name=\"prenom\" id=\"prenom\" value=\"'+pageClient.prenom+'\" required style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
            rep+= '	\n' ;
            rep+= '	                                <label for=\"email\"><b>Nom d\'utilisateur</b></label>\n' ;
            rep+='                                          <input type=\"text\" placeholder=\"Nom d\'utilisateur\" name=\"username\" id= \"username\" value=\"'+pageClient.username+'\" required style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
            rep+= '                                <label for=\"email\"><b>Courriel</b></label>\n' ;
            rep+='                                          <input type=\"text\" placeholder=\"Courriel\" name=\"mail\" id=\"mail\" value=\"'+pageClient.adrmail+'\" required style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
            rep+= '\n' ;
            rep+=' <div class=\"alert">';
            rep+='<span class=\"closebtn\" onclick="this.parentElement.style.display=\'none\';">&times;</span> ';
            rep+= '<strong>Attention!</strong>'+pageClient.msgMP+'</div>';
            rep+= '                                 <label for=\"psw\"><b>Mot de Pass</b></label>\n' ;
            rep+= '                                         <input type=\"password\" placeholder=\"Mot de Pass\" name=\"passe\" id=\"passe\"required style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
            rep+= '\n' ;
            rep+= '                                 <label for=\"psw-repeat\"><b>Confirmer</b></label>\n' ;
            rep+='                                          <input type=\"password\" placeholder=\"Confirmer\" name=\"confirmpasse\" required style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
            rep+='    \n' ;
            rep+='<br>'
            rep+='\n';
            rep+='<label>\n' ;
            rep+='</label>\n' ;
            rep+='\n';
            rep+= '                                 <label>\n' ;
            rep+= '                                         <input type=\"checkbox\" checked=\"checked\" name=\"remember\" style=\"margin-bottom:15px\"> Remember me\n' ;
            rep+='                                  </label>\n' ;
            rep+='                                          <input type=\"button\" value=\"Créer\"  onclick=\"requetes(\'inscription\',\'\',\'\',\'\'); \" style=\"color:white;font-weight: bold;font-size:20px;;\">\n' ;
            rep+= '                         </div>\n' ;
            rep+= '                 </form>\n' ;
            rep+='          <div style=\"text-align: center;\"><a onclick=\"AfficheformConnexion();\" href=\"#\" style=\"text-decoration-line: none \";><h6> Client existant?s\'enregistrer</h6></a>\n' ;
            rep+='          </div>\n' ;
            rep+='</div>\n' ;
        }
        if(pageClient.mesgErrConne){
                var rep= '<div class=\"topnav \" id=\"myTopnav\"  style=\"background-color:#0000de\"; >\n' ;
                rep+='       <a href=\"index.html\"   >Accueill</a>\n' ;
                rep+= '             <div class=\"dropdown\">\n' ;
                rep+= '                 <button class=\"dropbtn\">Gratuit et Échange\n' ;
                rep+= '                      <i class=\"fa fa-caret-down\"></i>\n' ;
                rep+='                  </button>\n' ;
                rep+= '                     <div class=\"dropdown-content\">\n' ;
                rep+= '                       <a href=\"#\">Je cherche</a>\n' ;
                rep+= '                       <a class=\"border\" href=\"#\">J\'offre</a>\n' ;
                rep+= '                     </div>\n' ;
                rep+= '            </div>\n' ;
                rep+='       <a href=\"#contact\">Emplois</a>\n' ;
                rep+= '             <div class=\"dropdown\">\n' ;
                rep+= '                   <button class=\"dropbtn\">Immobilier\n' ;
                rep+='                          <i class=\"fa fa-caret-down\"></i>\n' ;
                rep+= '                   </button>\n' ;
                rep+='                         <div class=\"dropdown-content\">\n' ;
                rep+='                            <a href=\"#\">Sous location</a>\n' ;
                rep+= '                           <a href=\"#\" class=\"border\">Location</a>\n' ;
                rep+= '                           <a href=\"#\" class=\"border\">Colocataire</a>\n' ;
                rep+='                        </div>\n' ;
                rep+='              </div> \n';
                rep+= '      <a href=\"#news\">Forum</a>\n' ;
                rep+= '            <div class=\"dropdown\">\n' ;
                rep+= '                 <button class=\"dropbtn\">Service\n' ;
                rep+= '                     <i class=\"fa fa-caret-down\"></i>\n' ;
                rep+='                  </button>\n' ;
                rep+='                       <div class=\"dropdown-content\">\n' ;
                rep+= '	                           <a href=\"#news\">Information</a>\n' ;
                rep+= '                            <a href=\"#\" class=\"border\">Covoiturage</a>\n' ;
                rep+= '                            <a href=\"#\" class=\"border\">Livraison</a>\n' ;
                rep+= '                     </div>\n' ;
                rep+= '             </div> \n' ;
                rep+='      <div class=\"w3-right\"><a onclick=\"AfficheformInscription()\" href=\"#\">Inscription</a></div>\n' ;
                rep+= '	    <div class=\"w3-right\"><a onclick=\"AfficheformConnexion()\" href=\"#\">Connection</a></div> \n' ;
                rep+='          <a href=\"javascript:void(0);\" class=\"icon\"  onclick=\"myFunction()\"><i  class=\"fa fa-bars\"></i></a>\n' ;
                rep+='</div>';
                rep+= '<div class=\"w3-content\" style=\"max-width:500px;\">\n' ;
                rep+= '         <form id=\"formconnexion\"  enctype=\"multitype/form-data\">\n' ;
                rep+= '                 <div class=\"container \"style=\"text-align: center;\" >\n' ; 
                rep+=' <div class=\"alert">';
                rep+='<span class=\"closebtn\" onclick="this.parentElement.style.display=\'none\';">&times;</span> ';
                rep+= '<strong>Attention!</strong>'+pageClient.mesgErrConne+'</div>';
                rep+= '                          <h1><b>Se connecter</b></h1><br>\n' ;
                rep+='                           <label for=\"mail\"><b>Courriel</b></label>\n' ;
                rep+= '                             <input type=\"text\" placeholder=\"Courriel\" name=\"mail\" id=\"mail\" required style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
                rep+= '\n' ;
                rep+= '                          <label for=\"passe\"><b>Mot de Passe</b></label>\n' ;
                rep+= '                             <input type=\"password\" placeholder=\"Mot de Pass\" name=\"passe\" id=\"passe\" required style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
                rep+= '	\n' ;
                rep+= '                         <input type=\"button\" value=\"Connecter\" onclick=\"requetes(\'connexion\',\'\',\'\')\" style=\"color:white;font-weight: bold;font-size:18px;\">\n' ;
                rep+= '                </div>\n' ;
                rep+= '        </form>\n' ;
                rep+= '	<div style=\"text-align: center;\"><a onclick=\"AfficheformInscription()\" href=\"#\" style=\"text-decoration-line: none\";><h6> Nouveau client? Créer un compte</h6></a></div>\n' ;
                rep+= '</div>' ;
          //  }else{
                /*if(pageClient.mesgDonne){
                    var rep= '<div class=\"topnav \" id=\"myTopnav\"  style=\"background-color:#0000de\"; >\n' ;
                rep+='       <a href=\"index.html\"   >Accueill</a>\n' ;
                rep+= '             <div class=\"dropdown\">\n' ;
                rep+= '                 <button class=\"dropbtn\">Gratuit et Échange\n' ;
                rep+= '                      <i class=\"fa fa-caret-down\"></i>\n' ;
                rep+='                  </button>\n' ;
                rep+= '                     <div class=\"dropdown-content\">\n' ;
                rep+= '                       <a href=\"#\">Je cherche</a>\n' ;
                rep+= '                       <a class=\"border\" href=\"#\">J\'offre</a>\n' ;
                rep+= '                     </div>\n' ;
                rep+= '            </div>\n' ;
                rep+='       <a href=\"#contact\">Emplois</a>\n' ;
                rep+= '             <div class=\"dropdown\">\n' ;
                rep+= '                   <button class=\"dropbtn\">Immobilier\n' ;
                rep+='                          <i class=\"fa fa-caret-down\"></i>\n' ;
                rep+= '                   </button>\n' ;
                rep+='                         <div class=\"dropdown-content\">\n' ;
                rep+='                            <a href=\"#\">Sous location</a>\n' ;
                rep+= '                           <a href=\"#\" class=\"border\">Location</a>\n' ;
                rep+= '                           <a href=\"#\" class=\"border\">Colocataire</a>\n' ;
                rep+='                        </div>\n' ;
                rep+='              </div> \n';
                rep+= '      <a href=\"#news\">Forum</a>\n' ;
                rep+= '            <div class=\"dropdown\">\n' ;
                rep+= '                 <button class=\"dropbtn\">Service\n' ;
                rep+= '                     <i class=\"fa fa-caret-down\"></i>\n' ;
                rep+='                  </button>\n' ;
                rep+='                       <div class=\"dropdown-content\">\n' ;
                rep+= '	                           <a href=\"#news\">Information</a>\n' ;
                rep+= '                            <a href=\"#\" class=\"border\">Covoiturage</a>\n' ;
                rep+= '                            <a href=\"#\" class=\"border\">Livraison</a>\n' ;
                rep+= '                     </div>\n' ;
                rep+= '             </div> \n' ;
                rep+='      <div class=\"w3-right\"><a onclick=\"AfficheformInscription()\" href=\"#\">Inscription</a></div>\n' ;
                rep+= '	    <div class=\"w3-right\"><a onclick=\"AfficheformConnexion()\" href=\"#\">Connection</a></div> \n' ;
                rep+='          <a href=\"javascript:void(0);\" class=\"icon\"  onclick=\"myFunction()\"><i  class=\"fa fa-bars\"></i></a>\n' ;
                rep+='</div>';

                rep+= '<div class=\"w3-container \" style=\"margin-right:420px;margin-left:420px;margin-top:20px;margin-bottom:20px\">\n' ;
                rep+= '         <form id=\"formconnexion\"  enctype=\"multitype/form-data\">\n' ;
                rep+= '                 <div class=\"container \"style=\"text-align: center;\" >\n' ; 
                rep+=' <div class=\"alert">';
                rep+='<span class=\"closebtn\" onclick="this.parentElement.style.display=\'none\';">&times;</span> ';
                rep+= '<strong>Attention!</strong>'+pageClient.mesgErrConne+'</div>';
                rep+= '                          <h1><b>Se connecter</b></h1><br>\n' ;
                rep+='                           <label for=\"mail\"><b>Courriel</b></label>\n' ;
                rep+= '                             <input type=\"text\" placeholder=\"Courriel\" name=\"mail\" id=\"mail\" required style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
                rep+= '\n' ;
                rep+= '                          <label for=\"passe\"><b>Mot de Passe</b></label>\n' ;
                rep+= '                             <input type=\"password\" placeholder=\"Mot de Pass\" name=\"passe\" id=\"passe\" required style=\"color:black;font-size:18px;font-weight: bold;\">\n' ;
                rep+= '	\n' ;
                rep+= '                         <input type=\"button\" value=\"Connecter\" onclick=\"requetes(\'connexion\',\'\',\'\')\" style=\"color:white;font-weight: bold;font-size:18px;\">\n' ;
                rep+= '                </div>\n' ;
                rep+= '        </form>\n' ;
                rep+= '	<div style=\"text-align: center;\"><a onclick=\"AfficheformInscription()\" href=\"#\" style=\"text-decoration-line: none\";><h6> Nouveau client? Créer un compte</h6></a></div>\n' ;
                rep+= '</div>' ;*/
         }else{
             if(pageClient.rep){//repense pour page client
    
           
   var rep='<div class=\"topnav \" id=\"myTopnav\"  style=\"background-color:#0000de\"; >\n';
    rep+= '    <a href=\"#\" onclick=\"Requetes(\'index\',\'\')\"   >Accueill</a>\n' ;
    rep+= '           <div class=\"dropdown \">\n';
    rep+= '                    <button class=\"dropbtn\" onclick=\"requtes(\'ListerCategorie\',\'donneesechange\',\'\',\'\')\">Gratuit et Échange\n' ;
    rep+= '                         <i class=\"fa fa-caret-down\"></i>\n' ;
    rep+= '                    </button>\n' ;
    rep+= '                   <div class=\"dropdown-content\">\n' ;
    rep+= '                     <a href=\"#\" onclick=\"(\'ListerCategorieTable\',\'donneesechange\',\'Je cherche\',\'\')\" >Je cherche</a>\n' ;
    rep+= '                     <a class=\"border\" href=\"#\"onclick=\"(\'ListerCategorieTable\',\'donneesechange\',\'J\'offre\',\'\')\"  >J\'offre</a>\n';
    rep+='                    </div>\n' ;
    rep+= '           </div>\n' ;
    rep+= '    <a href=\"#\" onclick=\"requtes(\'ListerCategorie\',\'emplois\',\'\',\'\')\">Emplois</a>\n' ;
    rep+='            <div class=\"dropdown\">\n' ;
    rep+= '                 <button onclick=\"requtes(\'ListerCategorie\',\'immobilier\',\'\',\'\')\" class=\"dropbtn\">Immobilier\n' ;
    rep+= '                    <i class=\"fa fa-caret-down\"></i>\n' ;
    rep+= '                  </button>\n' ;
    rep+= '               <div class=\"dropdown-content\">\n' ;
    rep+= '                 <a href=\"#\" onclick=\"(\'ListerCategorieTable\',\'immobilier\',\'sous location\',\'\')\">Sous location</a>\n' ;
    rep+= '                 <a href=\"#\" onclick=\"(\'ListerCategorieTable\',\'immobilier\',\'location\',\'\')\"  class=\"border\">Location</a>\n' ;
    rep+='                  <a href=\"#\" onclick=\"(\'ListerCategorieTable\',\'immobilier\',\'colocataire\',\'\')\" class=\"border\">Colocataire</a>\n' ;
    rep+= '              </div>\n' ;
    rep+='            </div> \n' ;
    rep+= '    <a href=\"#news\">Forum</a>\n' ;
    rep+='            <div class=\"dropdown\">\n' ;
    rep+= '                  <button onclick=\"requtes(\'ListerCategorie\',\'service\',\'\',\'\')\" class=\"dropbtn\">Service\n' ;
    rep+='                       <i class=\"fa fa-caret-down\"></i>\n' ;
    rep+= '                  </button>\n' ;
    rep+= '               <div class=\"dropdown-content\">\n' ;
    rep+='	                 <a href=\"#news\" onclick=\"AfficherInformation()\">Information</a>\n' ;
    rep+= '                   <a href=\"#\" onclick=\"(\'ListerCategorieTable\',\'service\',\'gardient\',\'\')\" class=\"border\">Gardient</a>\n' ;
    rep+='                    <a href=\"#\" onclick=\"(\'ListerCategorieTable\',\'service\',\'covoiturage\',\'\')\" class=\"border\">Covoiturage</a>\n' ;
    rep+= '                   <a href=\"#\" onclick=\"(\'ListerCategorieTable\',\'service\',\'livraison\',\'\')\" class=\"border\">Livraison</a>\n' ;
    rep+= '              </div>\n' ;
    rep+= '           </div>  \n' ;
    rep+='      <div class=\"w3-right\"><a   href=\"#\">'+pageClient.username +'</a></div>\n' ;//onclik pour afficher inscription et connexion
    rep+='	   <div class=\"w3-right\"><img src=\"profile/'+pageClient.image+'\" class=\"avatar\" alt=\"Avatar\"></div>\n' ;
    rep+= '<div class=\"w3-right\"><a href=\"#\">Déconnecter</a></div>\n';
    rep+= '\n' ;
    rep+='      <a href=\"javascript:void(0);\" class=\"icon\"  onclick=\"myFunction()\"><i  class=\"fa fa-bars\"></i></a>\n' ;
    rep+= '</div>\n' ;
    
    rep+= '<div class=\"w3-container \"  style=\"margin-right:120px;margin-left:220px\">\n' ;
    rep+= '        <div class=\"gallery w3-hover-shadow \"  style=\"width:220px;height:auto;\" >\n' ;
    rep+= '               <a href=\"francisation.html\"  >\n' ;
    rep+= '                   <img src=\"images/frenchclass.jpg\" alt=\"Cinque Terre\" >\n' ;
    rep+= '               </a>\n' ;
    rep+='                   <div class=\"desc\" ><span style=\"font-weight:normal;font-size:18px;\">Francisation</span></div>\n' ;
    rep+= '                   \n' ;
    rep+= '          </div>\n' ;
    rep+= '                   \n' ;
    rep+= '           <div class=\"gallery w3-hover-shadow\"  style=\"width:200px;height:auto;\">\n' ;
    rep+='                   <a target=\"_blank\" href=\"img_forest.jpg\">\n' ;
    rep+='                       <img src=\"images/frenchclass.jpg\" alt=\"Forest\" >\n' ;
    rep+= '                  </a>\n' ;
    rep+= '                  <div class=\"desc\">Add a description of the image here</div>\n' ;
    rep+= '          </div>\n' ;
    rep+= '             \n' ;
    rep+= '          <div class=\"gallery w3-hover-shadow\">\n' ;
    rep+='                      <a target=\"_blank\" href=\"img_lights.jpg\">\n' ;
    rep+= '                         <img src=\"images/d2.png\" alt=\"Northern Lights\" >\n' ;
    rep+= '                     </a>\n' ;
    rep+= '                     <div class=\"desc\">Add a description of the image here</div>\n' ;
    rep+= '          </div>\n' ;
    rep+= '                \n' ;
    rep+= '          <div class=\"gallery w3-hover-shadow\">\n' ;
    rep+='                  <a target=\"_blank\" href=\"img_mountains.jpg\">\n' ;
    rep+= '                       <img src=\"images/d2.png\" alt=\"Mountains\" >\n' ;
    rep+= '                </a>\n' ;
    rep+= '                <div class=\"desc\">Add a description of the image here</div>\n' ;
    rep+= '          </div>\n' ;
    rep+= '          <div class=\"gallery w3-hover-shadow\">\n' ;
    rep+='                   <a target=\"_blank\" href=\"img_mountains.jpg\">\n' ;
    rep+='                      <img src=\"images/d2.png\" alt=\"Mountains\" >\n' ;
    rep+= '                 </a>\n' ;
    rep+= '                 <div class=\"desc\">Add a description of the image here</div>\n' ;
    rep+= '         </div>\n' ;
    rep+= '</div>\n' ;
    rep+= '\n' ;
    rep+= ' <!-- hr--> \n' ;
    rep+= '<hr >\n' ;
    rep+='<hr >\n' ;
          if(pageClient.inscr){     //affiher page memebre avec message de filicitation d 'inscription
        rep+='<div class=\"succes\">';
        rep+='<span class=\"closebtn\" onclick=\"this.parentElement.style.display=\'none\';\">&times;</span> ';
        rep+='<strong>Félicitation!</strong> inscription avec succès.</div>';
        }
    rep+= '    <!-- Grid --> \n' ;
    rep+= '  <div class=\"w3-center w3-padding-16 \" style=\"margin-bottom:50px\">\n' ;
rep+= '       <span class=\"w3-xlarge w3-bottombar w3-border-dark-grey w3-padding-16\">Categorie</span>\n' ;
rep+= '      </div>\n' ;
rep+= '  	  <div class=\"w3-container w3-display-container\"  style=\"margin-bottom:50px\" >\n' ;
//debut de boucle
    for(i=0; i<=2; i++ ){
rep+= '   <div class=\"w3-row \"    style=\"margin-right:120px;margin-left:120px;margin-bottom:40px\" >\n' ; 
rep+= ' 	<div class=\"w3-quarter w3-margin-top  \"> \n' ;
rep+= '    <div class=\"w3-display-container   shadow w3-round-medium	\" style=\"width:80%\">\n' ;
rep+= '      <img src=\"Annonce/'+pageClient.donneesechanges[i].Image+'\" alt=\"Avatar\"  style=\"width:100%\"  class=\"w3-round-medium\">\n' ; 
rep+= ' 	    <div class=\"desc\" ><span style=\"font-weight:normal;font-size:18px;\">'+pageClient.donneesechanges[i].Titre+'</span></div> \n' ; 
rep+= '    <div class=\"w3-display-middle  w3-large	 \" > \n' ;
rep+= ' 			      <a  href=\"description.html\" style=\"text-decoration:none;\">\n' ;
rep+= '        <button class=\"w3-btn opacity button1 \" style=\"color:white;\"><b>Description</b></button>\n' ;
rep+= ' 	  </a>\n' ; 
rep+= '      </div> \n' ;
rep+= '   </div> \n' ; 
rep+= '   </div> \n' ;
rep+= '      <div class=\"w3-quarter w3-margin-top  \">\n' ; 
rep+= '   <div class=\"w3-display-container shadow w3-round-medium	\" style=\"width:80%\">\n' ;
rep+= '      <img src=\"Annonce/'+pageClient.service[i].Image+'\" alt=\"Avatar\"  style=\"width:100%\"  class=\"w3-round-medium\">\n' ;
rep+= ' 	    <div class=\"desc\" ><span style=\"font-weight:normal;font-size:18px;\"><p>'+pageClient.service[i].Titre+'</p><p>prix:'+pageClient.service[i].prix+'</span></div> \n' ;
rep+= '  <div class=\"w3-display-middle  w3-large	 \" >\n' ; 
rep+= ' 			      <a  href=\"description.html\" style=\"text-decoration:none;\">\n' ; 
rep+= ' <button class=\"w3-btn opacity button1 \" style=\"color:white;\"><b>Detail</b></button> \n' ; 
rep+= ' </a>\n' ; 
rep+= '     </div>\n' ;
rep+= ' </div> \n' ; 
rep+= '   </div> \n' ; 
rep+= '      <div class=\"w3-quarter w3-margin-top  \"> \n' ;
rep+= '   <div class=\"w3-display-container shadow w3-round-medium	\" style=\"width:80%\">\n' ;
rep+= '     <img src=\"Annonce/'+pageClient.Emplois[i].image+'\" alt=\"Avatar\"  style=\"width:100%\"  class=\"w3-round-medium\">\n' ;
rep+= ' 	    <div class=\"desc\" ><span style=\"font-weight:normal;font-size:18px;\"><p>'+pageClient.Emplois[i].titre+'</p><p>Prix:'+pageClient.Emplois[i].prix+'</p></span></div> \n' ;
rep+= '    <div class=\"w3-display-middle  w3-large	 \" >\n' ;
rep+= ' 			      <a  href=\"description.html\" style=\"text-decoration:none;\"> \n' ;
rep+= '   <button class=\"w3-btn opacity button1 \" style=\"color:white;\"><b>Description</b></button> \n' ;
rep+= '  </a> \n' ;
rep+= '   </div> \n' ; 
rep+= ' </div>  \n' ;
rep+= '  </div> \n' ;
rep+= '     <div class=\"w3-quarter w3-margin-top  \"> \n' ;
rep+= '  <div class=\"w3-display-container shadow w3-round-medium	\" style=\"width:80%\"> \n' ;
rep+= '    <img src=\"Annonce/'+pageClient.immobilier[i].Image+'\" alt=\"Avatar\"  style=\"width:100%\"  class=\"w3-round-medium\"> \n' ; 
rep+= '     <div class=\"desc\" ><span style=\"font-weight:normal;font-size:18px;\"><p>'+pageClient.immobilier[i].titre+'</p><p>Prix:'+pageClient.immobilier[i].prix+'</p></span></div> \n' ; 
rep+= '   <div class=\"w3-display-middle  w3-large	 \" > \n' ;
rep+= ' 			      <a  href=\"description.html\" style=\"text-decoration:none;\"> \n' ;
rep+= '     <button class=\"w3-btn opacity button1 \" style=\"color:white;\"><b>Description</b></button> \n' ;
rep+= ' 	  </a> \n' ;
rep+= '   </div> \n' ;
rep+= '  </div>   \n' ;
rep+= '  </div> \n' ;
rep+= '  </div> \n' ;
    }
///la fin de boucle
/*rep+= '  <div class=\"row\"  style=\"margin-right:120px;margin-left:120px;margin-bottom:40px\"> n' ;
rep+= '   <div class=\"w3-quarter w3-margin-top  \"> n' ;
rep+= '  <div class=\"w3-display-container   shadow w3-round-medium	\" style=\"width:80%\"> n' ;
rep+= '     <img src=\"job5.jpg\" alt=\"Avatar\"  style=\"width:100%\"  class=\"w3-round-medium\"> n' ;
rep+= ' 		    <div class=\"desc\" ><span style=\"font-weight:normal;font-size:18px;\">Titre</span></div> n' ;
rep+= '      <div class=\"w3-display-middle  w3-large	 \" > n' ;
rep+= ' 			      <a  href=\"description.html\" style=\"text-decoration:none;\">n' ; 
rep+= '      <button class=\"w3-btn opacity button1 \" style=\"color:white;\"><b>Description</b></button> n' ;
rep+= ' 	  </a> n' ;
rep+= '     </div> n' ;
rep+= '    </div>  </div> n' ;
rep+= '      <div class=\"w3-quarter w3-margin-top  \"> n' ;
rep+= '   <div class=\"w3-display-container shadow w3-round-medium	\" style=\"width:80%\"> n' ;
rep+= '     <img src=\"job6.jpg\" alt=\"Avatar\"  style=\"width:100%\"  class=\"w3-round-medium\">n' ; 
rep+= ' 		    <div class=\"desc\" ><span style=\"font-weight:normal;font-size:18px;\">Titre</span></div> n' ;
rep+= '    <div class=\"w3-display-middle  w3-large	 \" > n' ;
rep+= ' <a  href=\"description.html\" style=\"text-decoration:none;\"> n' ; 
rep+= '       <button class=\"w3-btn opacity button1 \" style=\"color:white;\"><b>Description</b></button> n' ;
rep+= ' 	  </a> n' ;
rep+= '     </div> n' ;
rep+= '   </div>  </div> n' ;
rep+= '       <div class=\"w3-quarter w3-margin-top  \"> n' ;
rep+= '   <div class=\"w3-display-container shadow w3-round-medium	\" style=\"width:80%\"> n' ; 
rep+= '     <img src=\"job7.jpg\" alt=\"Avatar\"  style=\"width:100%\"  class=\"w3-round-medium\"> n' ;
rep+= '  		    <div class=\"desc\" ><span style=\"font-weight:normal;font-size:18px;\">Titre</span></div> n' ; 
rep+= '     <div class=\"w3-display-middle  w3-large	 \" > n' ;
rep+= ' 				      <a  href=\"description.html\" style=\"text-decoration:none;\"> n' ;
rep+= '       <button class=\"w3-btn opacity button1 \" style=\"color:white;\"><b>Description</b></button> n' ;
rep+= ' 	  </a> n' ; 
rep+= '    </div>n' ;
rep+= '   </div>  </div> n' ;
rep+= ' <div class=\"w3-quarter w3-margin-top  \">n' ; 
rep+= '   <div class=\"w3-display-container shadow w3-round-medium	\" style=\"width:80%\"> n' ;
rep+= '    <img src=\"job8.jpg\" alt=\"Avatar\"  style=\"width:100%\"  class=\"w3-round-medium\"> n' ;
rep+= ' 		    <div class=\"desc\" ><span style=\"font-weight:normal;font-size:18px;\">Titre</span></div> n' ;
rep+= '     <div class=\"w3-display-middle  w3-large	 \" >n' ; 
rep+= ' 			      <a  href=\"description.html\" style=\"text-decoration:none;\"> n' ; 
rep+= '       <button class=\"w3-btn opacity button1 \" style=\"color:white;\"><b>Description</b></button> n' ;
rep+= '   </a> n' ;
rep+= ' </div> n' ;
rep+= '   </div>  </div> n' ;
rep+= '  </div> n' ;
rep+= ' </div> n' ;*/
rep+= '  </div> \n' ;
    }
 }
}
 document.getElementById("affichage").innerHTML = rep;	

}

